### ISSUE TITLE
Have waiting info always

### ISSUE THREAD

**Issue by algorys** [dnsmichi/manubulon-snmp#4]
Hello,

I've just download your plugins and I'm trying to getting work only check_snmp_storage for the moment. But when I try to use it, I have always the same answer : "Waiting for info"....

Here is my command line : 
./check_snmp_storage.pl -H 192.168.1.139 -w 70 -c 90 -m C: -C public

Is there a problem ? Or I have to install something else on hosts ?

Thanks in advance.

**Comment by Nicotyrox** [comment]
Try a snmpwalk to your host, this is caused by a timeout

**Comment by feld** [comment]
I'm seeing the same problem. A bulk walk works fine. This is only happening on a FreeBSD system with ZFS, from what I can tell, but I'm still attempting to debug this further to see exactly where it's hanging.

From what I can tell it's stuck at

            $resultat = $session->get_table($index_table);

**Comment by feld** [comment]
Ok, getting closer. If I use the index table -i I get results, but an error because it doesn't know what / is (root filesystem)

<pre>
Filter : /
OID : 1.3.6.1.2.1.25.2.3.1.1.1, Desc : 1
OID : 1.3.6.1.2.1.25.2.3.1.1.10, Desc : 10
OID : 1.3.6.1.2.1.25.2.3.1.1.2, Desc : 2
OID : 1.3.6.1.2.1.25.2.3.1.1.3, Desc : 3
OID : 1.3.6.1.2.1.25.2.3.1.1.31, Desc : 31
OID : 1.3.6.1.2.1.25.2.3.1.1.32, Desc : 32
OID : 1.3.6.1.2.1.25.2.3.1.1.33, Desc : 33
OID : 1.3.6.1.2.1.25.2.3.1.1.34, Desc : 34
OID : 1.3.6.1.2.1.25.2.3.1.1.35, Desc : 35
OID : 1.3.6.1.2.1.25.2.3.1.1.36, Desc : 36
OID : 1.3.6.1.2.1.25.2.3.1.1.37, Desc : 37
OID : 1.3.6.1.2.1.25.2.3.1.1.38, Desc : 38
OID : 1.3.6.1.2.1.25.2.3.1.1.39, Desc : 39
OID : 1.3.6.1.2.1.25.2.3.1.1.40, Desc : 40
OID : 1.3.6.1.2.1.25.2.3.1.1.41, Desc : 41
OID : 1.3.6.1.2.1.25.2.3.1.1.42, Desc : 42
OID : 1.3.6.1.2.1.25.2.3.1.1.43, Desc : 43
OID : 1.3.6.1.2.1.25.2.3.1.1.44, Desc : 44
OID : 1.3.6.1.2.1.25.2.3.1.1.45, Desc : 45
OID : 1.3.6.1.2.1.25.2.3.1.1.46, Desc : 46
OID : 1.3.6.1.2.1.25.2.3.1.1.47, Desc : 47
OID : 1.3.6.1.2.1.25.2.3.1.1.48, Desc : 48
OID : 1.3.6.1.2.1.25.2.3.1.1.49, Desc : 49
OID : 1.3.6.1.2.1.25.2.3.1.1.50, Desc : 50
OID : 1.3.6.1.2.1.25.2.3.1.1.51, Desc : 51
OID : 1.3.6.1.2.1.25.2.3.1.1.52, Desc : 52
OID : 1.3.6.1.2.1.25.2.3.1.1.53, Desc : 53
OID : 1.3.6.1.2.1.25.2.3.1.1.54, Desc : 54
OID : 1.3.6.1.2.1.25.2.3.1.1.55, Desc : 55
OID : 1.3.6.1.2.1.25.2.3.1.1.56, Desc : 56
OID : 1.3.6.1.2.1.25.2.3.1.1.57, Desc : 57
OID : 1.3.6.1.2.1.25.2.3.1.1.58, Desc : 58
OID : 1.3.6.1.2.1.25.2.3.1.1.59, Desc : 59
OID : 1.3.6.1.2.1.25.2.3.1.1.6, Desc : 6
OID : 1.3.6.1.2.1.25.2.3.1.1.60, Desc : 60
OID : 1.3.6.1.2.1.25.2.3.1.1.61, Desc : 61
OID : 1.3.6.1.2.1.25.2.3.1.1.62, Desc : 62
OID : 1.3.6.1.2.1.25.2.3.1.1.63, Desc : 63
OID : 1.3.6.1.2.1.25.2.3.1.1.7, Desc : 7
OID : 1.3.6.1.2.1.25.2.3.1.1.8, Desc : 8
OID : 1.3.6.1.2.1.25.2.3.1.1.9, Desc : 9
storages selected : 0
Unknown storage : / : ERROR
</pre>

**Comment by dnsmichi** [comment]
Did you find a solution for your problem?

**Comment by algorys** [comment]
@dnsmichi for me the problem is solved by setting right my snmp conf on ubuntu server :wink: . So no more problem.

**Comment by dnsmichi** [comment]
Ok thanks :)
